default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hacktive_development

production:
  <<: *default
  database: hacktive_production

staging:
  <<: *default
  database: hacktive_staging

test:
  <<: *default
  database: hacktive_test
